version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meridian-sql
    user: root
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql/data
    networks:
      - meridian_network

  redis:
    image: redis:latest
    container_name: meridian-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - meridian_network

  mysql:
    image: mysql:8.0
    container_name: meridian-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_db
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - meridian_network

  user-service:
    build:
      context: ./src/UserService/UserService.API
      dockerfile: Dockerfile
    container_name: meridian-user-service
    restart: always
    ports:
      - "6007:6007"
    environment:
      - ASPNETCORE_URLS=http://+:6007
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__UserDb=Server=mysql;Port=3306;Database=user_db;Uid=root;Pwd=root;
      - Jwt__Secret=meridian-super-secret-jwt-signing-key-32chars
      - Jwt__Issuer=meridian-gateway
      - Jwt__Audience=meridian-api
    depends_on:
      - mysql
    networks:
      - meridian_network

  api-gateway:
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    container_name: meridian-api-gateway
    restart: always
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Secret=meridian-super-secret-jwt-signing-key-32chars
      - Jwt__Issuer=meridian-gateway
      - Jwt__Audience=meridian-api
    depends_on:
      - user-service
    networks:
      - meridian_network

volumes:
  sqldata:
  redisdata:
  mysqldata:


networks:
  meridian_network:
    driver: bridge
